server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth
              uri: lb://auth
              predicates:
                - Path=/auth/**
              filters:
                - SetRequestHeader=X-Gateway-Secret, ${gateway.internal-secret}
            - id: modulo-alumnos
              uri: lb://modulo-alumnos
              predicates:
                - Path=/alumnos/**
              filters:
                - SetRequestHeader=X-Gateway-Secret, ${gateway.internal-secret}
            - id: modulo-cursos
              uri: lb://modulo-cursos
              predicates:
                - Path=/cursos/**
              filters:
                - SetRequestHeader=X-Gateway-Secret, ${gateway.internal-secret}
            - id: modulo-administracion
              uri: lb://modulo-administracion
              predicates:
                - Path=/personal/**
              filters:
                - SetRequestHeader=X-Gateway-Secret, ${gateway.internal-secret}
eureka:
  client:
    service-url:
      defaultZone: http://registry:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
